export const ADD_TODO = "todo/add_todo"
export const DELETE_TODO = "todo/delete-todo"
export const COMPLETE_A_TODO = "todo/complete_a_todo"
export const INCOMPLETE_A_TODO = "todo/incomplete_a_todo"
export const COMPLETE_ALL_TODO = "todo/complete_all_todo"
export const CLEAR_COMPLETED_TODO = "todo/clear_completed_todo"
export const UPDATE_COLOR_OF_TODO = "todo/update_color_of_todo"